a=3
try:
    assert (a==2)
except:
    print("fail")
finally:
    print("final")


